# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(609, 340)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setAutoFillBackground(False)
        self.username_textbox = QtWidgets.QLineEdit(Dialog)
        self.username_textbox.setGeometry(QtCore.QRect(140, 60, 113, 20))
        self.username_textbox.setObjectName("username_textbox")
        self.username_label = QtWidgets.QLabel(Dialog)
        self.username_label.setGeometry(QtCore.QRect(30, 60, 101, 16))
        self.username_label.setObjectName("username_label")
        self.password_textbox = QtWidgets.QLineEdit(Dialog)
        self.password_textbox.setGeometry(QtCore.QRect(140, 100, 113, 20))
        self.password_textbox.setInputMethodHints(QtCore.Qt.ImhDate|QtCore.Qt.ImhHiddenText)
        self.password_textbox.setInputMask("")
        self.password_textbox.setText("")
        self.password_textbox.setObjectName("password_textbox")
        self.password_label = QtWidgets.QLabel(Dialog)
        self.password_label.setGeometry(QtCore.QRect(30, 100, 71, 16))
        self.password_label.setObjectName("password_label")
        self.domain_label = QtWidgets.QLabel(Dialog)
        self.domain_label.setGeometry(QtCore.QRect(30, 150, 71, 16))
        self.domain_label.setObjectName("domain_label")
        self.domain_textbox = QtWidgets.QLineEdit(Dialog)
        self.domain_textbox.setGeometry(QtCore.QRect(140, 150, 113, 20))
        self.domain_textbox.setObjectName("domain_textbox")
        self.id_label = QtWidgets.QLabel(Dialog)
        self.id_label.setGeometry(QtCore.QRect(400, 60, 41, 16))
        self.id_label.setObjectName("id_label")
        self.id_textbox = QtWidgets.QLineEdit(Dialog)
        self.id_textbox.setGeometry(QtCore.QRect(440, 60, 113, 20))
        self.id_textbox.setObjectName("id_textbox")
        self.severname_textbox = QtWidgets.QLineEdit(Dialog)
        self.severname_textbox.setGeometry(QtCore.QRect(440, 110, 113, 20))
        self.severname_textbox.setObjectName("severname_textbox")
        self.servername_label = QtWidgets.QLabel(Dialog)
        self.servername_label.setGeometry(QtCore.QRect(323, 110, 120, 16))
        self.servername_label.setObjectName("servername_label")
        self.get_password_pushbutton = QtWidgets.QPushButton(Dialog)
        self.get_password_pushbutton.setGeometry(QtCore.QRect(220, 240, 131, 23))
        self.get_password_pushbutton.setObjectName("get_password_pushbutton")
        self.hours_textbox = QtWidgets.QLineEdit(Dialog)
        self.hours_textbox.setGeometry(QtCore.QRect(440, 150, 113, 20))
        self.hours_textbox.setText("")
        self.hours_textbox.setObjectName("hours_textbox")
        self.hours_label = QtWidgets.QLabel(Dialog)
        self.hours_label.setGeometry(QtCore.QRect(374, 150, 60, 16))
        self.hours_label.setObjectName("hours_label")
        self.comments_textbox = QtWidgets.QLineEdit(Dialog)
        self.comments_textbox.setGeometry(QtCore.QRect(440, 180, 113, 20))
        self.comments_textbox.setText("")
        self.comments_textbox.setObjectName("comments_textbox")
        self.comments_label = QtWidgets.QLabel(Dialog)
        self.comments_label.setGeometry(QtCore.QRect(344, 180, 91, 16))
        self.comments_label.setObjectName("comments_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.username_label.setText(_translate("Dialog", "User Name :"))
        self.password_label.setText(_translate("Dialog", "Password :"))
        self.domain_label.setText(_translate("Dialog", "Domain :"))
        self.id_label.setText(_translate("Dialog", "ID :"))
        self.servername_label.setText(_translate("Dialog", "Server name :"))
        self.get_password_pushbutton.setText(_translate("Dialog", "Get Password"))
        self.hours_label.setText(_translate("Dialog", "Hours :"))
        self.comments_label.setText(_translate("Dialog", "Comments :"))
